dist: bionic
language: rust
rust:
  - stable
cache: cargo
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  - rm -rf target/test
before_install:
  - sudo apt-get -y install libglu1-mesa libgl1-mesa-glx libgtk-3-0 xvfb
before_script:
- rustup component add rustfmt
script:
- xvfb-run cargo test --verbose -p sbnf
- cargo fmt -- --check
