[package]
name = "sublime-bnf"
version = "0.1.0"
authors = ["Benjamin Schaaf <ben.schaaf@gmail.com>"]
edition = "2018"

[dependencies]
indexmap = "1.3.2"

[dev-dependencies]
maplit = "1.0.2"
matches = "0.1.8"
