[package]
name = "sbnf"
version = "0.1.0"
authors = ["Benjamin Schaaf <ben.schaaf@gmail.com>"]
edition = "2018"

[[test]]
name = "syntax_tests"
harness = false

[dependencies]
indexmap = "1.3.2"

[dependencies.clap]
version = "~2.27.0"
default-features = false
features = [ "wrap_help" ]

[dev-dependencies]
maplit = "1.0.2"
matches = "0.1.8"
