[package]
name = "sbnfc"
version = "0.2.0"
edition = "2018"

[[bin]]
name = "sbnf"
path = "src/main.rs"

[dependencies]
sbnf = { version = "0.3.1", path = "../" }

[dependencies.clap]
version = "~2.27.0"
default-features = false
features = [ "wrap_help" ]
